\# DevOps Practical - Docker PHP



\## Objective

Install PHP inside Ubuntu container using Docker.



\## Commands Used



Pull Ubuntu:

docker pull ubuntu



Run Container:

docker run -it --name a2 ubuntu



Install PHP:

apt update

apt install php -y



Commit Container:

docker commit a2 jasleen1108/apt:v2



Push Image:

docker push jasleen1108/apt:v2


